source "https://rubygems.org"

gem "importmap-rails"
gem "perron", github: "Rails-Designer/perron"
gem "propshaft"
gem "puma", ">= 5.0"
gem "rails", "~> 8.1.2"
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
end
